#!/bin/sh

# arguments: no args for full screen, s for interactive selection, and w for current window
out_file=~/Pictures/screenshot-$(date +%F--%H:%M:%S).png

case $1 in
  s) maim_params=-s;;
  w) maim_params="-i $(xdotool getactivewindow)";;
  *) maim_params=;;
esac

eval maim -u $maim_params | tee $out_file | xclip -sel clip -t image/png && notify-send "Screenshot taken! 📸" "Saved to: $out_file"
